server:
  port: 8090
spring:
  application:
    name: saga-microservices
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  #datasource:
   # username: root
    #password: root
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/microservices_db
    #driver-class-name: com.mysql.jdbc.Driver
    #jpa:
     # properties:
      #  hibernate:
       #   dialect=org:
        #    hibernate:
         #     dialect:
          #      MySQL8Dialect: org.hibernate.dialect.MySQL8Dialect


#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: admin
  password: admin